apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobresources.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                command:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: jobresources
    singular: jobresource
    kind: JobResource
    shortNames:
    - jr
